before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: XcqDSktSfTb2059sjbsPtAniwk1uLD1pYicU1JcMebGD2n1eR0uY9scvd71NDHBSV9cZk/c5nfxJi9cSqt0Qf1R7alw6amvG9YKiQy/08khYeoDNjaP+bK8sf5C206L6APxfEcZGCWVPD2EoqeOisHyVttlsyOOpdNuShcU2h9CkfPSpyvYn9pI04kft52iO0y5qJVIx3djBx11dwXxjdp/8DElO/2uOkLOvbGPIISSJTEywma4j6h9ya+WIklN38G0nNLHQ5xznpmsnHbskErv9NPe/E5QbshiRTyfUbt0GMQhZSs/bWFBfE+asm7VLqU86iiAorlNHaBEZo9QtFOvbThpqv6uRkXVSh0+Pa6H7d8UzNw8Jd0yPwMrT4N7+pFogJGVkgr+Z9e37vMSAdz93IdKOKAUBMkoN7psdJhd0pYwqiDrxcgKD7Zq5ot4qoP2xdwNNPbWnKcGPFT+6IUlEcpWPP0R7I+YY2WWudyulcCzo3iT7RlTR9RzYzln/1HA4ueH9fEd/8AQTE2nXAzs36CLQF9DW6fw1QV5Lzzw43SroGoYZBXnlcfsTOsKwwSGdiAG1xpxC2noGTuQiC3jEIriCBdc3kDTH3qhFiFFU210jmeO7TemlCpNxS2cOKAsvQkVjRkXPeEXTtOwey+ZRsBgww75jvYw0EB6RXYc= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
